metadata:
  name: amd64-ubuntu

platform:
    name: linux/amd64

pipeline:
- crystal_build:
    image: ubuntu
    commands:
    - apt-get update
    - apt-get -y install --no-install-recommends build-essential ca-certificates curl git gnupg2
    - curl -sL "https://keybase.io/crystal/pgp_keys.asc" | apt-key add -
    - echo "deb http://dist.crystal-lang.org/apt crystal main" >   /etc/apt/sources.list.d/crystal.list
    - apt-get update
    - apt-get -y install --no-install-recommends crystal llvm-dev libgmp-dev libz-dev libssl1.0-dev
    - shards install --production
    - shards build --release
- docker_build:
    image: docker:git
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /root/.docker/config.json:/root/.docker/config.json:ro
    commands:
        - docker version
        - docker build . -f Dockerfile -t yukimochi/pub_relay:ubuntu-amd64
        - docker push yukimochi/pub_relay:ubuntu-amd64
